//! Parse a PEP 740 provenance object far enough to (1) name the *publisher* the
//! upstream index (PyPI) attested, and (2) check that its attestation is about
//! the exact bytes this server stores.
//!
//! pypiron does NO cryptography — it relays attestations verbatim (a
//! `.provenance` companion only ever exists on mirror-origin files; first-party
//! attestations are refused fail-closed). The `publisher` object inside a bundle
//! is generated by the *publishing* index and records the Trusted Publisher *it*
//! verified. We surface it on the human page attributed to that index ("as
//! attested to the publishing index, not re-verified here") — never as something
//! pypiron itself verified.
//!
//! The one honest, dependency-free check we *can* make is a digest binding:
//! every attestation carries a DSSE envelope whose `statement` is a base64
//! in-toto statement naming `subject[].digest.sha256`. When that subject digest
//! equals the sha256 of the artifact we are serving, the relayed attestation is
//! demonstrably about *these* bytes (a swapped or mismatched `.provenance`
//! companion is caught). That is an integrity match, not a signature check, and
//! is reported as such. Pure and best-effort: any malformed input yields no
//! publisher and/or no binding claim — never a panic.

use base64::Engine;
use serde_json::Value;

/// A relayed provenance object, reduced to what the page renders: the attested
/// publisher, plus whether that attestation is bound to the served bytes.
#[derive(Debug, Clone, PartialEq)]
pub struct Provenance {
    pub publisher: Publisher,
    /// True when some relayed attestation's in-toto subject sha256 matches the
    /// artifact's own sha256 — the relayed attestation is about *this* file.
    /// Never implies signature verification.
    pub digest_bound: bool,
    /// `Some` when at least one relayed attestation *fully verifies* offline
    /// against the trust root embedded in the binary — DSSE signature, Fulcio
    /// cert chain, SCT, Rekor transparency (bound to this entry), and subject-
    /// digest binding all pass (see [`crate::attest`]). The value is the signer
    /// identity drawn from the *verified certificate* — never the unsigned
    /// `publisher` field above. This is a genuine cryptographic verification
    /// pypiron performed itself, not a relayed claim; it implies `digest_bound`.
    pub verified_signer: Option<crate::attest::VerifiedSigner>,
}

/// The verified publishing identity drawn from a provenance attestation bundle.
#[derive(Debug, Clone, PartialEq)]
pub struct Publisher {
    /// Publisher kind, e.g. `GitHub`, `GitLab`, `Google`, `ActiveState`.
    pub kind: String,
    /// `owner/repo` for repo-backed publishers, when present.
    pub repository: Option<String>,
    /// Publishing workflow / job reference, when present.
    pub workflow: Option<String>,
    /// Deployment environment, when present.
    pub environment: Option<String>,
}

/// Parse provenance JSON bytes into the attested publisher *and* whether the
/// attestation is digest-bound to `artifact_sha256` (the sha256 of the file this
/// server serves). Best-effort: absent/malformed publisher yields `None`; a
/// bound check that cannot be made yields `digest_bound: false`, never a claim.
pub fn parse(bytes: &[u8], artifact_sha256: &str) -> Option<Provenance> {
    let v: Value = serde_json::from_slice(bytes).ok()?;
    let publisher = publisher_from_value(&v)?;
    let digest_bound = digest_binds(&v, artifact_sha256);
    // Independent, offline cryptographic verification against the embedded
    // Sigstore trust root. Fail-closed: any doubt yields `None` and the page
    // falls back to the relayed + digest-bound labeling.
    let verified_signer = crate::attest::verify(bytes, artifact_sha256);
    Some(Provenance {
        publisher,
        digest_bound,
        verified_signer,
    })
}

/// Parse provenance JSON bytes, returning the first bundle's publisher if one
/// with a non-empty `kind` is present.
pub fn parse_publisher(bytes: &[u8]) -> Option<Publisher> {
    let v: Value = serde_json::from_slice(bytes).ok()?;
    publisher_from_value(&v)
}

fn publisher_from_value(v: &Value) -> Option<Publisher> {
    let bundles = v.get("attestation_bundles")?.as_array()?;
    let pubv = bundles
        .iter()
        .filter_map(|b| b.get("publisher"))
        .find(|p| get_str(p, "kind").is_some())?;
    let kind = get_str(pubv, "kind")?;
    // PyPI carries publisher-specific fields at the top level of `publisher`;
    // older/minimal forms nest them under `claims`. Check both.
    let field = |name: &str| {
        get_str(pubv, name).or_else(|| pubv.get("claims").and_then(|c| get_str(c, name)))
    };
    Some(Publisher {
        repository: field("repository"),
        workflow: field("workflow").or_else(|| field("workflow_ref")),
        environment: field("environment"),
        kind,
    })
}

/// True when any relayed attestation's DSSE in-toto statement names a subject
/// whose sha256 digest equals `artifact_sha256` (case-insensitive hex). Binds
/// the relayed attestation to the exact stored bytes — a dependency-free
/// integrity match, NOT a signature verification. Best-effort: a malformed
/// envelope, undecodable statement, or absent subject contributes no match.
fn digest_binds(v: &Value, artifact_sha256: &str) -> bool {
    let want = artifact_sha256.trim();
    if want.is_empty() {
        return false;
    }
    v.get("attestation_bundles")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|b| b.get("attestations").and_then(Value::as_array))
        .flatten()
        .flat_map(attestation_subject_sha256s)
        .any(|d| d.eq_ignore_ascii_case(want))
}

/// The sha256 subject digests named by one attestation's DSSE statement. The
/// `envelope.statement` is a base64 in-toto statement; decode it, then read each
/// `subject[].digest.sha256`. Any failure along the way yields no digests.
fn attestation_subject_sha256s(att: &Value) -> Vec<String> {
    let Some(stmt_b64) = att.pointer("/envelope/statement").and_then(Value::as_str) else {
        return Vec::new();
    };
    let Ok(raw) = base64::engine::general_purpose::STANDARD.decode(stmt_b64.trim()) else {
        return Vec::new();
    };
    let Ok(stmt) = serde_json::from_slice::<Value>(&raw) else {
        return Vec::new();
    };
    stmt.get("subject")
        .and_then(Value::as_array)
        .map(|subs| {
            subs.iter()
                .filter_map(|s| s.pointer("/digest/sha256").and_then(Value::as_str))
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn get_str(v: &Value, key: &str) -> Option<String> {
    v.get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_github_style_publisher() {
        let json = br#"{"version":1,"attestation_bundles":[{"publisher":
            {"kind":"GitHub","repository":"brycedrennan/imaginAIry",
             "workflow":"release.yml","environment":"pypi"},"attestations":[]}]}"#;
        let p = parse_publisher(json).unwrap();
        assert_eq!(p.kind, "GitHub");
        assert_eq!(p.repository.as_deref(), Some("brycedrennan/imaginAIry"));
        assert_eq!(p.workflow.as_deref(), Some("release.yml"));
        assert_eq!(p.environment.as_deref(), Some("pypi"));
    }

    #[test]
    fn reads_fields_nested_under_claims() {
        let json = br#"{"attestation_bundles":[{"publisher":
            {"kind":"GitLab","claims":{"repository":"grp/proj","workflow_ref":"ci.yml"}}}]}"#;
        let p = parse_publisher(json).unwrap();
        assert_eq!(p.kind, "GitLab");
        assert_eq!(p.repository.as_deref(), Some("grp/proj"));
        assert_eq!(p.workflow.as_deref(), Some("ci.yml"));
        assert_eq!(p.environment, None);
    }

    #[test]
    fn minimal_publisher_keeps_only_kind() {
        let json = br#"{"attestation_bundles":[{"publisher":{"kind":"pytest","claims":{}},"attestations":[]}]}"#;
        let p = parse_publisher(json).unwrap();
        assert_eq!(p.kind, "pytest");
        assert_eq!(p.repository, None);
    }

    #[test]
    fn malformed_or_empty_yields_none() {
        assert_eq!(parse_publisher(b""), None);
        assert_eq!(parse_publisher(b"not json"), None);
        assert_eq!(parse_publisher(b"{}"), None);
        assert_eq!(parse_publisher(br#"{"attestation_bundles":[]}"#), None);
        // publisher present but kind blank → not usable
        assert_eq!(
            parse_publisher(br#"{"attestation_bundles":[{"publisher":{"kind":"  "}}]}"#),
            None
        );
    }

    /// Build a real-shaped PEP 740 provenance object: a publisher plus one
    /// attestation whose DSSE envelope carries a base64 in-toto statement naming
    /// `subject_sha256`. This is the exact structure PyPI's integrity API serves.
    fn provenance_with_subject(subject_sha256: &str) -> Vec<u8> {
        let statement = serde_json::json!({
            "_type": "https://in-toto.io/Statement/v1",
            "subject": [{
                "name": "pkg-1.0-py3-none-any.whl",
                "digest": {"sha256": subject_sha256},
            }],
            "predicateType": "https://docs.pypi.org/attestations/publish/v1",
            "predicate": null,
        });
        let stmt_b64 = base64::engine::general_purpose::STANDARD
            .encode(serde_json::to_vec(&statement).unwrap());
        serde_json::to_vec(&serde_json::json!({
            "version": 1,
            "attestation_bundles": [{
                "publisher": {"kind": "GitHub", "repository": "o/r", "workflow": "release.yml"},
                "attestations": [{
                    "version": 1,
                    "verification_material": {"certificate": "x", "transparency_entries": []},
                    "envelope": {"statement": stmt_b64, "signature": "sig"},
                }],
            }],
        }))
        .unwrap()
    }

    #[test]
    fn parse_binds_when_subject_digest_matches_artifact() {
        let sha = "c23e447ea90d796d1e645c35c4b2de125040add12a845825546f91c93f391b6b";
        let bytes = provenance_with_subject(sha);
        let prov = parse(&bytes, sha).unwrap();
        assert_eq!(prov.publisher.kind, "GitHub");
        assert!(prov.digest_bound, "matching subject sha must bind");
        // Case folds — a hex digest is compared case-insensitively.
        let prov_upper = parse(&bytes, &sha.to_ascii_uppercase()).unwrap();
        assert!(prov_upper.digest_bound);
    }

    #[test]
    fn parse_does_not_bind_on_subject_digest_mismatch() {
        let bytes = provenance_with_subject(
            "c23e447ea90d796d1e645c35c4b2de125040add12a845825546f91c93f391b6b",
        );
        // A different artifact sha — a swapped/mismatched provenance companion.
        let prov = parse(
            &bytes,
            "deadbeef00000000000000000000000000000000000000000000000000000000",
        )
        .unwrap();
        assert_eq!(prov.publisher.kind, "GitHub");
        assert!(!prov.digest_bound, "mismatched subject must not bind");
    }

    #[test]
    fn parse_does_not_bind_on_malformed_or_absent_envelope() {
        let sha = "c23e447ea90d796d1e645c35c4b2de125040add12a845825546f91c93f391b6b";
        // Statement is not valid base64.
        let junk_b64 = br#"{"attestation_bundles":[{"publisher":{"kind":"GitHub"},
            "attestations":[{"envelope":{"statement":"!!not base64!!"}}]}]}"#;
        let prov = parse(junk_b64, sha).unwrap();
        assert!(!prov.digest_bound);
        // No attestations at all (the minimal relayed shape): publisher, no bind.
        let no_att =
            br#"{"attestation_bundles":[{"publisher":{"kind":"pytest"},"attestations":[]}]}"#;
        let prov = parse(no_att, sha).unwrap();
        assert_eq!(prov.publisher.kind, "pytest");
        assert!(!prov.digest_bound);
        // A blank artifact sha never binds, even against a well-formed subject.
        let bytes = provenance_with_subject(sha);
        assert!(!parse(&bytes, "").unwrap().digest_bound);
        assert!(!parse(&bytes, "   ").unwrap().digest_bound);
    }
}
